name: Visual Dimensions
pygments: true
excerpt_separator: <!--more-->
prose:
  rooturl: "_posts"
  siteurl: "http://vizdimensions.phase2technology.com"
  media: "img"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "date"
        field:
          element: "text"
          label: "Published Date"