name: Visual Dimensions
pygments: true
excerpt_separator: <!--more-->
prose:
  rooturl: "_posts"
  siteurl: "http://vizdimensions.phase2technology.com"
  media: "img"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "date"
        field:
          element: "text"
          label: "Published Date"
          placeholder: "YYYY-MM-DD HH:MM:SS"
          help: "Format: YYYY-MM-DD HH:MM:SS (i.e., 2014-01-01 12:00:00)"
      - name: "video"
        field:
          element: "text"
          label: "Youtube Video"
          placeholder: "//www.youtube.com/embed/[videoid]"
          help: "Appears at the top of the post. Be sure to grab the snippet from the embed code on Youtube."